apiVersion: 1

contactPoints:
  - orgId: 1
    name: tm-errors-telegram
    receivers:
      - uid: tm_errors_telegram
        type: telegram
        disableResolveMessage: true
        settings:
          bottoken: "8434928677:AAFExlRKu3BtExeniLzfy-zeDLB1WrHraq0"
          chatid: "812527476"
          disable_notification: false
          message: '{{ template "tm.telegram.error_logs" . }}'
