apiVersion: 1

groups:
  - orgId: 1
    name: tm-errors-panel-only
    folder: TM
    interval: 1m
    rules:
      - uid: tm_errors_panel_logs_telegram
        title: TM Errors panel logs detected
        condition: B
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: loki
            model:
              datasource:
                type: loki
                uid: loki
              editorMode: code
              expr: 'topk(20, sum by (function, error_message) (count_over_time({job=~"lambda|.*lambda.*", function=~".*todomercado.*"} | json record="record" | line_format "{{.record}}" |~ "(?i)error" | regexp "(?P<error_message>.+)" | error_message != "" [5m])))'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: classic_conditions
        dashboardUid: tm-lambdas-overview
        panelId: 7
        noDataState: OK
        execErrState: Error
        for: 0m
        annotations:
          summary: Error log detectado en TodoMercado.
          count_5m: '{{ printf "%.0f" $values.A.Value }}'
          panel_url: 'https://grafana.deepzide.com/d/tm-lambdas-overview?viewPanel=7&var-lambda_name={{ $labels.function }}'
        labels:
          service: todomercado
          source: tm-errors-panel
          severity: critical
        notification_settings:
          receiver: tm-errors-telegram
        isPaused: false
