apiVersion: 1

templates:
  - orgId: 1
    name: tm.telegram.error_logs
    template: |-
      {{ define "tm.telegram.error_logs" -}}
      {{- if gt (len .Alerts.Firing) 0 -}}
      {{- range .Alerts.Firing }}
      TM ERROR LOG
      Lambda: {{ .Labels.function }}
      Errores (5m): {{ .Annotations.count_5m }}
      Mensaje: {{ .Labels.error_message }}
      Panel: {{ .Annotations.panel_url }}

      {{- end -}}
      {{- else -}}
      TM ALERT TEST
      Contact point Telegram operativo.
      {{- end -}}
      {{- end }}
