apiVersion: 1

templates:
  - orgId: 1
    name: tm.telegram.error_logs
    template: |-
      {{ define "tm.telegram.error_logs" -}}
      {{- if .Alerts.Firing -}}
      {{- range .Alerts.Firing }}
      TM ERROR LOG
      Lambda: {{ .Labels.function }}
      Errores (5m): {{ .Annotations.count_5m }}
      Mensaje: {{ .Labels.error_message }}
      Panel: {{ .Annotations.panel_url }}

      {{- end -}}
      {{- end -}}
      {{- end }}
