apiVersion: 1

templates:
  - orgId: 1
    name: tm.telegram.error_logs
    template: |-
      {{ define "tm.telegram.error_logs" -}}
      {{- if gt (len .Alerts.Firing) 0 -}}
      {{- range .Alerts.Firing }}
      TM ERROR LOG
      Lambda: {{ or .Labels.function "unknown-function" }}
      Errors (5m): {{ or .Annotations.count_5m .ValueString }}
      Message: {{ or .Labels.error_message .Annotations.summary "error without parsed message" }}
      Panel: {{ .Annotations.panel_url }}

      {{- end -}}
      {{- else -}}
      TM ALERT TEST
      Contact point Telegram operativo.
      {{- end -}}
      {{- end }}
